site_name: Wannier90
# site_url: https://example.com/
site_author: Wannier90 Developers
site_description: >-
  Everything about wannier90...

repo_name: wannier-developers/wannier90
repo_url: https://github.com/wannier-developers/wannier90
edit_uri: https://github.com/qiaojunfeng/w90-docs/edit/main/docs
view_uri: https://github.com/qiaojunfeng/w90-docs/raw/main/docs

copyright: Copyright &copy; 2016 - 2024 Wannier90 Developers

nav:
   - Home: 'index.md'
   - 'User guide':
      - 'Introduction': "user_guide/introduction.md"
      - 'wannier90.x':
        - "Methodology": "user_guide/wannier90/methodology.md"
        - "Parameters": "user_guide/wannier90/parameters.md"
        - "Projections": "user_guide/wannier90/projections.md"
        - "Code overview": "user_guide/wannier90/code_overview.md"
        - "Post-processing": "user_guide/wannier90/postproc.md"
        - "Library mode": "user_guide/wannier90/library_mode.md"
        - "Transport": "user_guide/wannier90/transport.md"
        - "Files": "user_guide/wannier90/files.md"
        - "Notes on interpolations": "user_guide/wannier90/notes_interpolations.md"
        - "Sample inputs": "user_guide/wannier90/sample_inputs.md"
      - 'postw90.x':
        - "Berry": "user_guide/postw90/berry.md"
        - "Gyrotropic": "user_guide/postw90/gyrotropic.md"
        - "BoltzWann": "user_guide/postw90/boltzwann.md"
        - "Generic Band interpolation": "user_guide/postw90/geninterp.md"
      - "Appendices": 
        - "Utilities": "user_guide/appendices/utilities.md"
        - "FAQs": "user_guide/appendices/faq.md"
   - 'Tutorials':
      - 'Preliminaries': "tutorial/preliminaries.md"
      - '1: Gallium Arsenide &#151; MLWFs for the valence bands': "tutorial/tutorial_1.md"
      - '2: Lead &#151; Wannier-interpolated Fermi surface': "tutorial/tutorial_2.md"
      - '3: Silicon &#151; Disentangled MLWFs': "tutorial/tutorial_3.md"
      - '4: Copper &#151; Fermi surface, orbital character of energy bands': "tutorial/tutorial_4.md"
      - 'Tutorials with the `pwscf` Interface': "tutorial/with_pwscf.md"
      - '5: Diamond &#151; MLWFs for the valence bands': "tutorial/tutorial_5.md"
      - '6: Copper &#151; Fermi surface': "tutorial/tutorial_6.md"
      - '7: Silane (SiH$$_4$$) &#151; Molecular MLWFs using $\Gamma$-point sampling': "tutorial/tutorial_7.md"
      - '8: Iron &#151; Spin-polarized WFs, DOS, projected WFs versus MLWFs': "tutorial/tutorial_8.md"
      - '9: Cubic BaTiO$_3$': "tutorial/tutorial_9.md"
      - '10: Graphite': "tutorial/tutorial_10.md"
      - '11: Silicon &#151; Valence and low-lying conduction states': "tutorial/tutorial_11.md"
      - '12: Benzene &#151; Valence and low-lying conduction states': "tutorial/tutorial_12.md"
      - '13: (5,5) Carbon Nanotube &#151; Transport properties': "tutorial/tutorial_13.md"
      - '14: Linear Sodium Chain &#151; Transport properties': "tutorial/tutorial_14.md"
      - '15: (5,0) Carbon Nanotube &#151; Transport properties': "tutorial/tutorial_15.md"
      - '16: Silicon &#151; Boltzmann transport': "tutorial/tutorial_16.md"
      - '17: Iron &#151; Spin-orbit-coupled bands and Fermi-surface contours': "tutorial/tutorial_17.md"
      - '18: Iron &#151; Berry curvature, anomalous Hall conductivity and optical conductivity': "tutorial/tutorial_18.md"
      - '19: Iron &#151; Orbital magnetization': "tutorial/tutorial_19.md"
      - '20: Disentanglement restricted inside spherical regions of k space': "tutorial/tutorial_20.md"
      - '21: Gallium Arsenide &#151; Symmetry-adapted Wannier functions': "tutorial/tutorial_21.md"
      - '22: Copper &#151; Symmetry-adapted Wannier function': "tutorial/tutorial_22.md"
      - '23: Silicon &#151; $G_0W_0$ bands structure interpolation': "tutorial/tutorial_23.md"
      - '24: Tellurium &#151; gyrotropic effect': "tutorial/tutorial_24.md"
      - '25: Gallium Arsenide &#151; Nonlinear shift current': "tutorial/tutorial_25.md"
      - '26: Gallium Arsenide &#151; Selective localization and constrained centres': "tutorial/tutorial_26.md"
      - '27: Silicon &#151; Selected columns of density matrix algorithm for automated MLWFs': "tutorial/tutorial_27.md"
      - '28: Diamond &#151; plotting of MLWFs using Gaussian cube format and VESTA': "tutorial/tutorial_28.md"
      - '29: Platinum &#151; Spin Hall conductivity': "tutorial/tutorial_29.md"

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wannier-developers/wannier90

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: wannier-developers
      repo: wannier90
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: qiaojunfeng/w90-docs
      branch: main
  - search
  - bibtex:
      bib_file: "refs.bib"
      footnote_format: "ref{number}" # default "{number}", to avoid conflict with user-defined footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/katex.js
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
